### ISSUE TITLE
Request for new release

### ISSUE THREAD

**Issue by gene1wood** [aegirhall/console-menu#28]
Would it be possible to render a new release (tag and pypi release) with the [changes that have gone in since a year ago at v0.5.1](https://github.com/aegirhall/console-menu/compare/v0.5.1...develop)?

I'd like to use the ability to pass in a `Screen` object to `consolemenu.SelectionMenu`

**Comment by aegirhall** [comment]
v0.6.0 released today (Sept 7, 2019).
