### ISSUE TITLE
Not an issue more of a usage question

### ISSUE THREAD

**Issue by asween16** [aegirhall/console-menu#36]
1. Is there a way to just have the menu scroll up instead of redisplay I am using it to list some info but the info gets blown away with the new display of the menu.

2. When creating a submenu. Is it possible to then add FunctionItems to the submenu instead of a list of Selections. Or do you simpy add the items the same way as you do in the main menu.

Thank you

**Comment by naveci** [comment]
1. for me, the following code fixed the issue. The documentation wasn't very clear on this, but some other issue in this repo provided me enough of an answer to get it working.

```python
import consolemenu as CM
from consolemenu.prompt_utils import PromptUtils

# Used for the enter_to_continue prompt before clearing the screen and spawning the menu.
screen = CM.Screen()

def someFunction():
    PromptUtils(screen).enter_to_continue()
```

2. You can just add functions to the submenu.
Example:
```python
submenu_1.append_item(CMI.FunctionItem("Function name in menu", functionNameWithoutParentheses))
```

**Comment by aegirhall** [comment]
Hi @asween16. In addition to @naveci's solution, v0.7.0 also supports passing clear_screen=False to the Menu constructor, so the automatic screen refresh will then be completely disabled.
