### ISSUE TITLE
Function Usage Question

### ISSUE THREAD

**Issue by kodaman2** [aegirhall/console-menu#47]
Maybe I am misunderstanding this package. It looks great, but for example I have setup a FunctionItem to call hello:

> Side note: None of the examples call another function like this. Just input.

```
def hello():
    print('Hello World')

    # also tried Screen with same results
    Screen.println('hello')
```

I select the correct number, and enter. It just goes on a loop and shows the menu again. The message printed is shown for a split second. What is the correct way to print lines onto the console so the user can see them?

**Comment by blksith0** [comment]
Yeah it seems this library is good for displaying menus, but only menus. No actual console output from the functions themselves. If you scroll up in the console you can see that it's there, but not well displayed.
