### ISSUE TITLE
How to properly exit the menu

### ISSUE THREAD

**Issue by gustavobsch** [aegirhall/console-menu#69]
Hi, after running a FunctionItem I want to stop the entire program. However the current behavior goes back to the previous menu once FunctionItem has completed.

What's the proper way to exit the entire program once FunctionItem has completed?

I'm currently using os._exit() to exit the program, not sure this is the clean way to do it. 

Thanks

**Comment by the1gofer** [comment]
checkout out [should_exit](https://console-menu.readthedocs.io/en/latest/consolemenu/items/FunctionItem.html)
