### ISSUE TITLE
Questions about the cascade sub menu

### ISSUE THREAD

**Issue by wangyihanlarry** [aegirhall/console-menu#76]
Hi,

Is there any way possible to create a serises of submenu, you know, we some times need mutliple level selections to reach to the desired page. like a wizard.

BR
Larry

**Comment by aegirhall** [comment]
Hi  @wangyihanlarry,

Yes, submenus can be many levels deep (there is no restriction on how many submenus you can have, other than system resource limitations, and UX best-practices :)

See the files in the "examples" folder to see several examples of using submenus.
